openapi: 3.0.0

info:
  title: Car Rental System
  version: 1.0.0

tags:
  - name: Daftar API

parameters:
  - in: body
    name: body
    description: Mobil baru yang akan didata
    required: true
    schema:
      $ref: '#/definitions/Cars'

responses:
  201:
    description: Mobil baru berhasil didata
    schema:
      $ref: '#/definitions/Cars'

definitions:
  Cars:
    type: object
    properties:
      model:
        type: string
      price_per_day:
        type: number
      availability:
        type: boolean
      required:
        - model
        - price_per_day
        - availability

