openapi: 3.0.0

info:
  title: Car Rental System
  version: 1.0.0

tags:
  - name: Daftar API

parameters:
  - in: body
    name: body
    description: Detail Transaksi yang akan dibuat
    required: true
    schema:
      $ref: '#/definitions/Rentals'

responses:
  201:
    description: Transaksi berhasil dibuat.
    schema:
      $ref: '#/definitions/Rentals'

definitions:
  Rentals:
    type: object
    properties:
      car_id:
        type: integer
      customer_name:
        type: string
      start_date:
        type: string
        format: date
      end_date:
        type: string
        format: date
      total_price:
        type: number
      required:
        - car_id
        - customer_name
        - start_date
        - end_date
        - total_price